'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Brands',
      [
        { name: "Aurora", image: 'aurora.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Avenli", image: 'avenli.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "amiciCucina", image: 'amici.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Black&Decker", image: 'black.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Briket", image: 'briket.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Blu", image: 'blu.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Cocinex", image: 'cocinex.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Codini", image: 'codini.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Columbia", image: 'columbia.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Conometal", image: 'conometal.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "CORVO", image: 'corvo.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Daewoo", image: 'daewoo.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "DeWalt", image: 'dewalt.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Diluvio", image: 'diluvio.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Discovery", image: 'discovery.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Drean", image: 'drean.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Electra", image: 'electra.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Electrolux", image: 'electrolux.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Enova", image: 'enova.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Escorial", image: 'escorial.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "EuroSound", image: 'eurosound.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Extreme", image: 'extreme.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "FAGOR", image: 'fagor.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Fedders", image: 'fedders.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "GAMA", image: 'gama.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Gravity", image: 'gravity.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "HEAD", image: 'head.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Hitachi", image: 'hitachi.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "HP", image: 'hp.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Hyundai", image: 'hyundai.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "iPhone", image: 'iphone.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Kanji", image: 'kanji.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "KanjiHome", image: 'kanjihome.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Ken Brown", image: 'kenbrown.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Kitchenaid", image: 'kitchen.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Kodak", image: 'kodak.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Kovea", image: 'kovea.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Lamborghini", image: 'lamborghini.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "LG", image: 'lg.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Liliana", image: 'liliana.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Lumer", image: 'lumer.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Lusqtoff", image: 'otros.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Magiclick", image: 'magiclick.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Mega Express", image: 'megaexpress.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Millenium", image: 'millenium.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Mor", image: 'mor.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Motorola", image: 'motorola.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Mountain Bike", image: 'mountainbike.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Noblex", image: 'noblex.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Panoramic", image: 'panoramic.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "PEABODY", image: 'peabody.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "PHILCO", image: 'philco.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "PlayStation", image: 'playstation.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "POCO", image: 'poco.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Quantum", image: 'quantum.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Ranser", image: 'ranser.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "RCA", image: 'rca.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Samsung", image: 'samsung.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Sherman", image: 'sherman.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Star Trak", image: 'startrak.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "STANLEY", image: 'stanley.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Teora", image: 'teora.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "TCL", image: 'tcl.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Ultracomb", image: 'ultracomb.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Universal", image: 'universal.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Vitta", image: 'vitta.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Westinghouse", image: 'westinghouse.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Whirlpool", image: 'whirlpool.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Xiaomi", image: 'xiaomi.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "YELMO", image: 'yelmo.svg', createdAt: new Date(), updatedAt: new Date() },
        { name: "Otros", image: 'otros.svg', createdAt: new Date(), updatedAt: new Date() },
      ],
      {});

  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Brands', null, {});

  }
};
